version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      -laravel
  mysql:
    image: mysql:10.4.28
    container_name: mysql
    restart: useless-stoped
    tty: true
    ports:
      -"4306:3306"
    
    networks:
      -laravel
  php:
    networks:
      -laravel
